// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILoVGExXIZBXxrwFgpzyjHjNoZ0WrKfU',
    appId: '1:899697179056:web:36e031d34ac16415ccfe75',
    messagingSenderId: '899697179056',
    projectId: 'wild-focus-9231c',
    authDomain: 'wild-focus-9231c.firebaseapp.com',
    storageBucket: 'wild-focus-9231c.firebasestorage.app',
    measurementId: 'G-13VWN1W8RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwf5TVKpFgKLZHs7LulndhLBTNwp8Tt0',
    appId: '1:899697179056:android:907bb04f37b60512ccfe75',
    messagingSenderId: '899697179056',
    projectId: 'wild-focus-9231c',
    storageBucket: 'wild-focus-9231c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy8mNKETemajKe8-BXILPhNodcbHaYxPQ',
    appId: '1:899697179056:ios:4c79bd84bcc4b23cccfe75',
    messagingSenderId: '899697179056',
    projectId: 'wild-focus-9231c',
    storageBucket: 'wild-focus-9231c.firebasestorage.app',
    iosBundleId: 'com.example.wildfocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy8mNKETemajKe8-BXILPhNodcbHaYxPQ',
    appId: '1:899697179056:ios:4c79bd84bcc4b23cccfe75',
    messagingSenderId: '899697179056',
    projectId: 'wild-focus-9231c',
    storageBucket: 'wild-focus-9231c.firebasestorage.app',
    iosBundleId: 'com.example.wildfocus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAILoVGExXIZBXxrwFgpzyjHjNoZ0WrKfU',
    appId: '1:899697179056:web:210755645f7f2feeccfe75',
    messagingSenderId: '899697179056',
    projectId: 'wild-focus-9231c',
    authDomain: 'wild-focus-9231c.firebaseapp.com',
    storageBucket: 'wild-focus-9231c.firebasestorage.app',
    measurementId: 'G-KNR8KV9VKV',
  );
}
